#file_topic = "files"
#file_buffer_dir = "" # temp directory for writing large temp files
#aws_access_key = ""
#aws_secret_key = ""

# bus options
#bus = "file" # options: stdio,file,nsq
#nsqd_hosts = ["localhost:4150"]
#lookupd_hosts = [""]
#topic = "deduper" # consumer topic
#channel = "deduper" # consumer topic channel

# launcher options
#max_in_progress = 1
#worker_timeout = "10s"
#lifetime_workers = 0 # no limit if set to 0
#done_topic = "done"
#enforced_task_type = "deduper"
