bus = "stdio" # options: stdio,file,nsq
# nsqd_hosts = ["localhost:4150"]
# lookupd_hosts = [""]


[[rule]]
  path_template = "s3://bucket/path/{YYYY}/{MM}/{DD}/{HH}/"
# lookback = 24    # the number of hours to lookback and check for files default is 24 hours
# frequency = "1h" # the time between checking the folder for new files default is 1h
