bus = "stdio" # options: stdio,file,nsq
#in_bus = "" # options: stdin,file,nsq
#out_bus = "" # options: stdout,file,nsq
#nsqd_hosts = ["localhost:4150"]
#lookupd_hosts = [""]
#topic = "sort2file" # consumer topic
#channel = "sort2file" # consumer topic channel

#max_in_progress = 1
#worker_kill_time = "10s"
#lifetime_workers = 0
#done_topic = "done"
#enforced_task_type = "" # if provided, incoming tasks are rejected if they don't match this type

#file_topic = "files"
#file_buffer_dir = "" # temp directory for writing large temp files
#aws_access_key = ""
#aws_secret_key = ""
